# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 16f365a30269fc529c62b1230de1bec6031dd7b143cfb0d900cfaff37f2a20eaf6744a37d5ff4986f033410cddc0c66464ba66d99bc400223f41b1e9ec995c22

test:
  secret_key_base: 1bd83017334bbc29e134e7bc3c2c8cd9959f1384057dd68ac9646ce1fd75e653c6e503c9559340f36407a93ec0a1b4b1686309a2da3411159839c0f442ea496f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
